# This file was generated by GoReleaser. DO NOT EDIT.
cask "lazybrew" do
  version "0.2.1"

  on_macos do
    on_intel do
      sha256 "42d942cf694b88618f6425bda62b8d9ff970f0cdc834ce2a925fce0048ad8517"
      url "https://github.com/todor-a/lazybrew/releases/download/v#{version}/lazybrew_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7863ae55a349ae3302582196a7f4ee7ba2594acad2dc648bab78fa1d144d4280"
      url "https://github.com/todor-a/lazybrew/releases/download/v#{version}/lazybrew_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "lazybrew"
  desc "Terminal UI for inspecting and uninstalling Homebrew packages"
  homepage "https://github.com/todor-a/lazybrew"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lazybrew"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lazybrew"]
    end
  end

  # No zap stanza required

end
