# This file was generated by GoReleaser. DO NOT EDIT.
cask "lazybrew" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "211198f7329f8fa325ae985ea61e15d19bf106a4928a8cf9f51889c468f11952"
      url "https://github.com/todor-a/lazybrew/releases/download/v#{version}/lazybrew_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "69fc918433ace132a0ad56914e49c3c39acfcd7012784780f87fb70728ba73b2"
      url "https://github.com/todor-a/lazybrew/releases/download/v#{version}/lazybrew_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "lazybrew"
  desc "Terminal UI for inspecting and uninstalling Homebrew packages"
  homepage "https://github.com/todor-a/lazybrew"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lazybrew"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lazybrew"]
    end
  end

  # No zap stanza required

end
