# This file was generated by GoReleaser. DO NOT EDIT.
cask "lazybrew" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "2aa91b4df88b9a3953d647d0a029c0d8982264652b8d3cc58cd40b2d23e96ab4"
      url "https://github.com/todor-a/lazybrew/releases/download/v#{version}/lazybrew_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "1d8749a1bcd67ae78a39bf5d8a35b956f83bb528c295d0e13b3a71f551383ecc"
      url "https://github.com/todor-a/lazybrew/releases/download/v#{version}/lazybrew_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "lazybrew"
  desc "Terminal UI for inspecting and uninstalling Homebrew packages"
  homepage "https://github.com/todor-a/lazybrew"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lazybrew"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lazybrew"]
    end
  end

  # No zap stanza required

end
